(package
  (name base64)
  (version "0.4.0")
  (license "BSD")
  (authors "Alex Shinn")
  (maintainers "Justin Ethier")
  (description "Implementation of Base64 encoding / decoding")
  (tags "networking")
  (docs "https://github.com/cyclone-scheme/cyclone-winds/wiki/base64")
  (test "test.scm")
  (dependencies ())
  (test-dependencies ())
  (foreign-dependencies ())
  (library
    (name (cyclone base64))
    (description "A library to encode and decode Base64")))
