(package
  (name base64)
  (version 0.2)
  (license "BSD")
  (authors "")
  (maintainers "")
  (description "")
  (tags "")
  (docs "https://github.com/cyclone-scheme/cyclone-winds/wiki/base64")
  (test "test.scm")
  (dependencies ())
  (test-dependencies ())
  (foreign-dependencies ())
  (library
    (name (cyclone base64))
    (description "")))
